name: "nix"
on:
  push:
    paths-ignore:
      - '.github/**'
      - '_img/**'
  workflow_dispatch:
jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: check if flake complies with default style
        run: nix fmt -- -c .
  check-eval:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: check if flake evaluates
        run: nix flake check
