name: "update-flake-inputs"
on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:
jobs:
  update-inputs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 1
      - name: Setup Git
        run: |
          git config --local user.name  "github-actions[bot]"
          git config --local user.email  "github-actions[bot]@users.noreply.github.com"
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@main
        with:
          token: ${{ secrets.FLAKE_UPDATE_PAT }}
          pr-title: "flake: update inputs"
          pr-assignees: alyraffauf
          pr-reviewers: mrgntamayo
          pr-labels: |
            dependencies
            automated