name: "nix-build"
on:
  push:
    paths-ignore:
      - '*.md'
      - '.github/**'
      - '_img/**'
  workflow_dispatch:
jobs:
  mandarin-build:
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
      - uses: actions/checkout@main
        with:
          fetch-depth: 1
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: cachix/cachix-action@master
      - name: Build fallarbor
        run: nix build --accept-flake-config .#nixosConfigurations.mandarin.config.system.build.toplevel
